"use client"; // Mark as client component to use usePathname

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { usePathname } from "next/navigation"; // Import usePathname
import "./globals.css";
import Header from "@/app/components/header/Header";
import Footer from "@/app/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Prepacademy",
//   description: "Generated by Pixelboho",
//   icons: {
//     icon: "/Headerlogo.png", 
//   },
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname(); // Get current route

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}>
        {/* Hide Header on "/hidden-page" */}
        {pathname !== "/blogdetails" && <Header />}
        <main className="w-full flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
