import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/header/Header";
import Footer from "@/app/components/footer/Footer";
import Head from "next/head"; // Import Head

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Prepacademy",
  description: "Generated by Pixelboho",
  icons: {
    icon: "/Headerlogo.png", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-black`}>
        <Header /> {/* ✅ Static Header on all pages */}
        <main className="w-full flex-1">{children}</main>
        <Footer /> {/* ✅ Static Footer on all pages */}
      </body>
    </html>
  );
}
